print("Guanyu Chen")
print("0953074")
print("09/01/2019")
print("MSITM 6341")
print()
print("Hello World!")
print()
print("My name is Guanyu Chen")
print()
print("This is my first Python program!")
print()
print("Have a nice day.")